### ISSUE TITLE
sqlite3.OperationalError

### ISSUE THREAD

**Issue by sktg84** [kaikoh95/crypto-trading-bot#1]
Some times in : https://github.com/kaikoh95/crypto-trading-bot/blob/main/db.py#L13 will throw the below error. 

Exception: (sqlite3.OperationalError) near "BTCUSDT": syntax error
[SQL: BTCUSDT]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

**Comment by sktg84** [comment]
def fetch_dataframe(symbol, engine):
    try:
        return pd.read_sql(symbol, engine)
    except Exception as ex:
        print (f'Exception: {ex}')

**Comment by kaikoh95** [comment]
> def fetch_dataframe(symbol, engine): try: return pd.read_sql(symbol, engine) except Exception as ex: print (f'Exception: {ex}')

Agreed, thanks for spotting it out :) 

Fixed in this commit (https://github.com/kaikoh95/crypto-trading-bot/commit/f849d17845e7f16516860e5a71d79fd5a8c95bd6)
