### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by CALZ28143** [kaikoh95/crypto-trading-bot#4]
Hello good day can you help me? Im from ph

**Comment by CALZ28143** [comment]
@kaikoh95 how can i download this file ? 😥

**Comment by BenSa0112** [comment]
Hi, 
this is not an installation file. You have to run the the script and change the .env file. First of all you have to install git and python. After that you can download the repo on a specific folder with "git clone https://github.com/kaikoh95/crypto-trading-bot.git" and run the script.
